// Generated by scripts/fetch-abis.mjs. Do not edit by hand.
// Source:   Sourcify, chain 4663
// Address:  0x3711ceA4feaDE896C913C68F01Eda97Cb06D1A42
// Contract: PonsV2LaunchDeployer
// Compiler: 0.8.35+commit.47b9dedd
// Match:    exact_match (verified 2026-08-04T17:41:17Z)
//
// `as const` is load-bearing: viem infers argument and return types from the
// literal ABI, and widening it to `Abi` throws that inference away.
export const launchDeployerAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "factory_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "name": "Create2EmptyBytecode",
    "type": "error",
    "inputs": []
  },
  {
    "name": "FailedDeployment",
    "type": "error",
    "inputs": []
  },
  {
    "name": "InsufficientBalance",
    "type": "error",
    "inputs": [
      {
        "name": "balance",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "needed",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "name": "MetadataTooLong",
    "type": "error",
    "inputs": []
  },
  {
    "name": "NotFactory",
    "type": "error",
    "inputs": []
  },
  {
    "name": "deployLaunch",
    "type": "function",
    "inputs": [
      {
        "name": "params",
        "type": "tuple",
        "components": [
          {
            "name": "pairToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "creatorFeeRecipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "originalDeployer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "feePolicy",
            "type": "address",
            "internalType": "contract IPonsV2FeePolicy"
          },
          {
            "name": "policy",
            "type": "tuple",
            "components": [
              {
                "name": "protocolFeeRecipient",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "protocolFeeShareBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "buybackBurnBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "hookFeeBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "maxInternalPriceImpactBps",
                "type": "uint16",
                "internalType": "uint16"
              }
            ],
            "internalType": "struct FeePolicySnapshot"
          },
          {
            "name": "feeEscrow",
            "type": "address",
            "internalType": "contract IPonsV2FeeEscrow"
          },
          {
            "name": "buybackVault",
            "type": "address",
            "internalType": "contract PonsV2BuybackVault"
          },
          {
            "name": "phantomQuote",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "curveFeeBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "creatorTaxBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "buybackEnabled",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "graduationThreshold",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "supply",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "salt",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "name",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "symbol",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "logo",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "description",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "socials",
            "type": "tuple",
            "components": [
              {
                "name": "twitter",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "telegram",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "discord",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "website",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "farcaster",
                "type": "string",
                "internalType": "string"
              }
            ],
            "internalType": "struct PonsV2LauncherToken.Socials"
          }
        ],
        "internalType": "struct LaunchDeployment"
      }
    ],
    "outputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "curve",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "name": "factory",
    "type": "function",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "name": "predictLaunchAddresses",
    "type": "function",
    "inputs": [
      {
        "name": "params",
        "type": "tuple",
        "components": [
          {
            "name": "pairToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "creatorFeeRecipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "originalDeployer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "feePolicy",
            "type": "address",
            "internalType": "contract IPonsV2FeePolicy"
          },
          {
            "name": "policy",
            "type": "tuple",
            "components": [
              {
                "name": "protocolFeeRecipient",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "protocolFeeShareBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "buybackBurnBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "hookFeeBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "maxInternalPriceImpactBps",
                "type": "uint16",
                "internalType": "uint16"
              }
            ],
            "internalType": "struct FeePolicySnapshot"
          },
          {
            "name": "feeEscrow",
            "type": "address",
            "internalType": "contract IPonsV2FeeEscrow"
          },
          {
            "name": "buybackVault",
            "type": "address",
            "internalType": "contract PonsV2BuybackVault"
          },
          {
            "name": "phantomQuote",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "curveFeeBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "creatorTaxBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "buybackEnabled",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "graduationThreshold",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "supply",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "salt",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "name",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "symbol",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "logo",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "description",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "socials",
            "type": "tuple",
            "components": [
              {
                "name": "twitter",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "telegram",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "discord",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "website",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "farcaster",
                "type": "string",
                "internalType": "string"
              }
            ],
            "internalType": "struct PonsV2LauncherToken.Socials"
          }
        ],
        "internalType": "struct LaunchDeployment"
      }
    ],
    "outputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "curve",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  }
] as const
